name: GlobalToast
main: SVega9848\GlobalToast\Main
version: 0.2.0
api: 4.0.0
authors: [SVega, BlusteryS]
description: Broadcast toast announcements to everyone in the server!

permissions:
  globaltoast.use:
    description: Broadcast toast announcements to everyone in the server!
    default: op
