# Plugin created by SVega - Check my YouTube channel! https://www.youtube.com/channel/UCOBOk07J93sqTlfjRzjThyQ
# Use & to set color format

# Title
toast-title: "          &l&bSVega's &r&3Server          "